### ISSUE TITLE
rename WdaF?

### ISSUE THREAD

**Issue by RnZ3** [mobiusTripper-crypto/beetswars-v2#61]
wdaf has no meaning - cold be a meme tho :-)
maybe there's a better name for it

**Comment by onkeljoe** [comment]
Something like "when to add fBEETS" or "add voting power before snapshot"

**Comment by RnZ3** [comment]
i thought about something simpler like "snapshot times" maybe but unsure

**Comment by RnZ3** [comment]
fixed with #74 if you all agree
